apiVersion: v1
kind: Service
metadata:
  name: nginx-status
  labels:
    app: nginx-status
spec:
  type: LoadBalancer
  ports:
    - name: nginx-status
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-status